version: '3.8'
services:
  consumer:
    build: ../rencana-studi
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
          "server.port" : "8088"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: